version: 0.0
os: linux

files:
<<<<<<< HEAD
  - source: /
    destination: /var/www/html

=======
  - source: index.html
    destination: /var/www/html/
>>>>>>> d9fc439 (Update appspec.yml)
hooks:
  BeforeInstall:
    - location: scripts/clean_directory.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

