version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Build stage running..."
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - index.html
